# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the specific script for this component
COPY src/train.py .

# Define the entrypoint for the container
ENTRYPOINT ["python", "train.py"]
